name: Build brython plugin
on:
  push:
    branches: main
    
jobs:
  Build-brython-plugin-for-acode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install --global yarn
    - run: npm install
    - run: yarn build --mode production
    - run: ls
    - name: Upload_video_artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./dist
        retention-days: 1
