name: Build brython plugin
on:
  push:
    branches: main
    
jobs:
  Build-brython-plugin-for-acode:
    runs-on: ubuntu-latest
    steps:
    - name: Yarn setup
      uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 16
    - run: yarn build --mode production
    - run: ls
